// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct Client {
    pub client_id: Identity,
    pub connected: bool,
}

impl TableType for Client {
    const TABLE_NAME: &'static str = "Client";
    type ReducerEvent = super::ReducerEvent;
}

impl TableWithPrimaryKey for Client {
    type PrimaryKey = Identity;
    fn primary_key(&self) -> &Self::PrimaryKey {
        &self.client_id
    }
}

impl Client {
    #[allow(unused)]
    pub fn filter_by_client_id(client_id: Identity) -> TableIter<Self> {
        Self::filter(|row| row.client_id == client_id)
    }
    #[allow(unused)]
    pub fn find_by_client_id(client_id: Identity) -> Option<Self> {
        Self::find(|row| row.client_id == client_id)
    }
    #[allow(unused)]
    pub fn filter_by_connected(connected: bool) -> TableIter<Self> {
        Self::filter(|row| row.connected == connected)
    }
}
