// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct CreatePlayerArgs {}

impl Reducer for CreatePlayerArgs {
    const REDUCER_NAME: &'static str = "create_player";
}

#[allow(unused)]
pub fn create_player() {
    CreatePlayerArgs {}.invoke();
}

#[allow(unused)]
pub fn on_create_player(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status) + Send + 'static,
) -> ReducerCallbackId<CreatePlayerArgs> {
    CreatePlayerArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let CreatePlayerArgs {} = __args;
        __callback(__identity, __addr, __status);
    })
}

#[allow(unused)]
pub fn once_on_create_player(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status) + Send + 'static,
) -> ReducerCallbackId<CreatePlayerArgs> {
    CreatePlayerArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let CreatePlayerArgs {} = __args;
        __callback(__identity, __addr, __status);
    })
}

#[allow(unused)]
pub fn remove_on_create_player(id: ReducerCallbackId<CreatePlayerArgs>) {
    CreatePlayerArgs::remove_on_reducer(id);
}
