// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct PlayerComponent {
    pub entity_id: u64,
    pub owner_id: Identity,
}

impl TableType for PlayerComponent {
    const TABLE_NAME: &'static str = "PlayerComponent";
    type ReducerEvent = super::ReducerEvent;
}

impl TableWithPrimaryKey for PlayerComponent {
    type PrimaryKey = u64;
    fn primary_key(&self) -> &Self::PrimaryKey {
        &self.entity_id
    }
}

impl PlayerComponent {
    #[allow(unused)]
    pub fn filter_by_entity_id(entity_id: u64) -> TableIter<Self> {
        Self::filter(|row| row.entity_id == entity_id)
    }
    #[allow(unused)]
    pub fn find_by_entity_id(entity_id: u64) -> Option<Self> {
        Self::find(|row| row.entity_id == entity_id)
    }
    #[allow(unused)]
    pub fn filter_by_owner_id(owner_id: Identity) -> TableIter<Self> {
        Self::filter(|row| row.owner_id == owner_id)
    }
    #[allow(unused)]
    pub fn find_by_owner_id(owner_id: Identity) -> Option<Self> {
        Self::find(|row| row.owner_id == owner_id)
    }
}
