// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use super::player_stances::PlayerStances;
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct UpdatePlayerStanceArgs {
    pub stance: PlayerStances,
}

impl Reducer for UpdatePlayerStanceArgs {
    const REDUCER_NAME: &'static str = "update_player_stance";
}

#[allow(unused)]
pub fn update_player_stance(stance: PlayerStances) {
    UpdatePlayerStanceArgs { stance }.invoke();
}

#[allow(unused)]
pub fn on_update_player_stance(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status, &PlayerStances) + Send + 'static,
) -> ReducerCallbackId<UpdatePlayerStanceArgs> {
    UpdatePlayerStanceArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let UpdatePlayerStanceArgs { stance } = __args;
        __callback(__identity, __addr, __status, stance);
    })
}

#[allow(unused)]
pub fn once_on_update_player_stance(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status, &PlayerStances) + Send + 'static,
) -> ReducerCallbackId<UpdatePlayerStanceArgs> {
    UpdatePlayerStanceArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let UpdatePlayerStanceArgs { stance } = __args;
        __callback(__identity, __addr, __status, stance);
    })
}

#[allow(unused)]
pub fn remove_on_update_player_stance(id: ReducerCallbackId<UpdatePlayerStanceArgs>) {
    UpdatePlayerStanceArgs::remove_on_reducer(id);
}
