// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use super::player_action::PlayerAction;
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct UpdatePlayerActionArgs {
    pub action: PlayerAction,
}

impl Reducer for UpdatePlayerActionArgs {
    const REDUCER_NAME: &'static str = "update_player_action";
}

#[allow(unused)]
pub fn update_player_action(action: PlayerAction) {
    UpdatePlayerActionArgs { action }.invoke();
}

#[allow(unused)]
pub fn on_update_player_action(
    mut __callback: impl FnMut(&Identity, Option<Address>, &Status, &PlayerAction) + Send + 'static,
) -> ReducerCallbackId<UpdatePlayerActionArgs> {
    UpdatePlayerActionArgs::on_reducer(move |__identity, __addr, __status, __args| {
        let UpdatePlayerActionArgs { action } = __args;
        __callback(__identity, __addr, __status, action);
    })
}

#[allow(unused)]
pub fn once_on_update_player_action(
    __callback: impl FnOnce(&Identity, Option<Address>, &Status, &PlayerAction) + Send + 'static,
) -> ReducerCallbackId<UpdatePlayerActionArgs> {
    UpdatePlayerActionArgs::once_on_reducer(move |__identity, __addr, __status, __args| {
        let UpdatePlayerActionArgs { action } = __args;
        __callback(__identity, __addr, __status, action);
    })
}

#[allow(unused)]
pub fn remove_on_update_player_action(id: ReducerCallbackId<UpdatePlayerActionArgs>) {
    UpdatePlayerActionArgs::remove_on_reducer(id);
}
